#!/usr/bin/env python3
"""Pin the campaign artifacts that Paper 1 no longer quotes.

check_manuscript_counts.py is scoped to the Paper 1 manuscript, so it stopped
reading the gauge, cascade, orbit, holonomy, natural-orbital and v103
artifacts when the manuscript stopped quoting them. Those numbers are still
shipped, still cited across docs/, and still the input to Paper 2, and every
one of them is regenerated by a script that can silently produce different
output: the gauge campaign already shipped a bug where rerunning it against
its own artifact reported zero improvements and dropped every exact-arithmetic
flag. This checker is the gate that caught that, kept alive on the artifacts
the manuscript checker released.

Reads results/data only. It does not read the manuscript.

  python scripts/check_data_consistency.py [--data DIR]
"""
from __future__ import annotations

import argparse
import json
import pathlib
import sys
from collections import Counter

from sympy import Matrix


ROOT = pathlib.Path(__file__).resolve().parents[1]
DATA = ROOT / "results/data"
STATES = DATA / "states.jsonl"

# Interference support topology: the loop census over the 156 interference
# records, and the two closure vertices whose kernel dimensions are quoted.
EXPECT_INTERFERENCE_DECOMP = dict(engine=142, audit_recovered=12, fiber_sparsified=2)
EXPECT_INTERFERENCE_TOTAL = 156
EXPECT_LOOPFREE_INTERFERENCE = 93
EXPECT_LOOP_CARRYING = 63
EXPECT_CLOSURE_KERNELS = {
    "(15,15,6,6,6,6,6,6,6,6)": 1,
    "(18,18,18,18,5,5,5,5,5,5)": 5,
}

EXPECT_HOLONOMY = dict(
    loopy_states=63,
    loops=82,
    degree_counts={"1": 37, "2": 32, "4": 13},
    exp_degree_counts={"1": 8, "2": 29, "4": 32, "8": 13},
    all_two_elementary=True,
    all_kernels_saturated=True,
    loops_with_radicand_outside_weight_group=15,
)
EXPECT_GAUGE = dict(
    states=799,
    certified_gauge_minimal=670,
    exterior_certificates_exact=799,
    strictly_improved_by_exterior_contractions=82,
    newly_certified_by_exterior_contractions=41,
    states_that_gauge_sparsify=0,
)
EXPECT_GAUGE_OPEN = 129
EXPECT_CASCADE = dict(
    states_with_support_drop=71,
    total_amplitudes_removed=89,
    multiplicity_drift_blocked=33,
    drops_by_class={"INTERFERENCE": 71},
)
EXPECT_CASCADE_RESIDUAL = 2.3e-16
# The characteristic-polynomial identity is conjugation invariant, so "exactly
# recognized" is not "attains the vertex": zero endpoints are attainers and all
# 71 are exact on the spectrum locus only.
EXPECT_CASCADE_EXACT = dict(
    endpoints_attempted=71,
    certified_s_Q_NO=0,
    exact_spectrum_only_s_Q_free=71,
)
EXPECT_ORBIT = dict(
    endpoints_tested=71,
    same_state_as_library=63,
    new_states_found=8,
    endpoints_in_natural_orbital_basis=0,
)
EXPECT_V103_S10 = dict(
    state_denominator=46852,
    squared_weights=[
        "13/34", "5/34", "53/442", "195/1802", "5/68",
        "5/68", "35/901", "1/34", "18/901", "84/11713",
    ],
    support=10,
    certified_library_support=14,
)
EXPECT_V103_FREE_OFFDIAGONALS = {"rho[3,9]": "-5/68", "rho[1,6]": "-sqrt(42)/221"}
EXPECT_NO_LEDGER = dict(
    records=156,
    support_grew=141,
    support_unchanged=15,
    support_shrank=0,
    already_natural_orbital=2,
)
EXPECT_NO_RATIO_ABOVE = 141
EXPECT_NO_RATIO_FLAT = 13
EXPECT_FIBER_SYMMETRIES = dict(
    records=799,
    pair_minor_certificates=799,
    full_column_rank=799,
    rank_failures=0,
    transport_classes=403,
    positive_incidence_kernel_records=63,
    positive_incidence_kernel_transport_classes=39,
    positive_kernel_pair_map_failures=0,
)


def load(name: str, data: pathlib.Path = DATA):
    return json.loads((data / name).read_text())


def kernel_dim(support_dets) -> int:
    orbitals = sorted({m for det in support_dets for m in det})
    matrix = Matrix([[1 if m in det else 0 for m in orbitals] for det in support_dets])
    return len(matrix.T.nullspace())


def check_block(name: str, got: dict, want: dict, errors: list[str]) -> None:
    for key, expected in want.items():
        if got.get(key) != expected:
            errors.append(f"{name} {key}: expected {expected}, got {got.get(key)}")


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument(
        "--data",
        type=pathlib.Path,
        default=DATA,
        help="artifact directory to check (defaults to results/data)",
    )
    data = parser.parse_args(argv).data
    records = [
        json.loads(line)
        for line in (data / "states.jsonl").read_text().splitlines()
        if line
    ]
    errors: list[str] = []

    if sum(EXPECT_INTERFERENCE_DECOMP.values()) != EXPECT_INTERFERENCE_TOTAL:
        errors.append("interference decomposition does not sum to its total")

    kernels = Counter()
    for record in records:
        if record["classified"] != "INTERFERENCE":
            continue
        kernels[kernel_dim([tuple(t) for t in record["closed_form"]["support_dets"]])] += 1
    loop_free = kernels[0]
    loop_carrying = sum(count for dim, count in kernels.items() if dim > 0)
    if loop_free != EXPECT_LOOPFREE_INTERFERENCE:
        errors.append(
            f"loop-free interference supports: expected "
            f"{EXPECT_LOOPFREE_INTERFERENCE}, got {loop_free}"
        )
    if loop_carrying != EXPECT_LOOP_CARRYING:
        errors.append(
            f"loop-carrying interference supports: expected "
            f"{EXPECT_LOOP_CARRYING}, got {loop_carrying}"
        )

    for record in records:
        key = "(" + ",".join(map(str, record["integer_form"])) + ")"
        if key in EXPECT_CLOSURE_KERNELS:
            got = kernel_dim([tuple(t) for t in record["closed_form"]["support_dets"]])
            if got != EXPECT_CLOSURE_KERNELS[key]:
                errors.append(
                    f"closure vertex {key}: expected kernel dimension "
                    f"{EXPECT_CLOSURE_KERNELS[key]}, got {got}"
                )

    check_block(
        "holonomy", load("holonomy_fields.json", data)["summary"], EXPECT_HOLONOMY, errors
    )

    gauge = load("gauge_min_summary.json", data)
    check_block("gauge", gauge, EXPECT_GAUGE, errors)
    open_rows = gauge.get("states", 0) - gauge.get("certified_gauge_minimal", 0)
    if open_rows != EXPECT_GAUGE_OPEN:
        errors.append(
            f"gauge open rows: expected {EXPECT_GAUGE_OPEN}, got {open_rows}"
        )

    cascade = load("cascade_summary.json", data)
    for key in ("states_with_support_drop", "total_amplitudes_removed", "drops_by_class"):
        if cascade.get(key) != EXPECT_CASCADE[key]:
            errors.append(
                f"cascade {key}: expected {EXPECT_CASCADE[key]}, got {cascade.get(key)}"
            )
    drift = cascade.get("blocked_reasons", {}).get("multiplicity_drift")
    if drift != EXPECT_CASCADE["multiplicity_drift_blocked"]:
        errors.append(
            f"cascade multiplicity-drift count: expected "
            f"{EXPECT_CASCADE['multiplicity_drift_blocked']}, got {drift}"
        )
    if not cascade.get("worst_residual_among_drops", 1) <= EXPECT_CASCADE_RESIDUAL:
        errors.append("cascade worst residual exceeds its recorded bound")
    v103_rows = [
        row for row in cascade.get("cancellation_regime_members", [])
        if row.get("index") == 103
    ]
    if not (
        v103_rows
        and v103_rows[0].get("support_certified") == 14
        and v103_rows[0].get("support_upper") == 10
    ):
        errors.append("cascade v103 support 14 -> 10 disagrees")

    check_block("cascade_exact", load("cascade_exact.json", data), EXPECT_CASCADE_EXACT, errors)
    check_block("orbit_check", load("orbit_check.json", data), EXPECT_ORBIT, errors)

    # The support-10 certificate is SUPERSEDED by design: its state is not
    # diagonal, so its diagonality check is expected to be False. What must
    # hold is the exact spectrum-locus content and the superseded marking.
    v103 = load("v103_support10_certificate.json", data)
    if v103.get("state_denominator") != EXPECT_V103_S10["state_denominator"]:
        errors.append("v103 support-10 state denominator disagrees")
    if sorted(v103.get("squared_weights", [])) != sorted(EXPECT_V103_S10["squared_weights"]):
        errors.append("v103 support-10 squared weights disagree")
    if len(v103.get("support_dets", [])) != EXPECT_V103_S10["support"]:
        errors.append("v103 support-10 support size disagrees")
    if v103.get("certified_library_support") != EXPECT_V103_S10["certified_library_support"]:
        errors.append("v103 library support 14 disagrees")
    if v103.get("status") != "SUPERSEDED":
        errors.append("v103 support-10 certificate should be marked SUPERSEDED")
    if v103.get("checks", {}).get("charpoly_identity_exact") is not True:
        errors.append("v103 support-10 certificate lost its exact charpoly identity")
    if v103.get("checks", {}).get("rdm_is_exactly_diagonal") is not False:
        errors.append("v103 support-10 certificate should record a NON-diagonal 1-RDM")

    # Both off-diagonal entries are pinned: quoting only one of them was a
    # review finding, because one entry alone does not separate s_Q^free from
    # s_Q^NO.
    free = load("v103_sqfree_certificate.json", data)
    if free.get("status") != "CURRENT":
        errors.append("v103 s_Q^free certificate should be marked CURRENT")
    if free.get("claim") != "s_Q^free(v103) <= 10":
        errors.append("v103 s_Q^free certificate carries the wrong claim")
    for key in (
        "spectrum_equals_lambda",
        "weights_all_rational",
        "weights_sum_to_one",
        "real_up_to_gauge",
    ):
        if free.get(key) is not True:
            errors.append(f"v103 s_Q^free certificate lost check {key}")
    if free.get("rdm_is_diagonal") is not False:
        errors.append("v103 s_Q^free certificate should record a NON-diagonal 1-RDM")
    off_diagonals = free.get("rdm_nonzero_offdiagonals", {})
    for entry, value in EXPECT_V103_FREE_OFFDIAGONALS.items():
        if off_diagonals.get(entry) != value:
            errors.append(f"v103 off-diagonal {entry}: expected {value}")

    check_block(
        "natural-orbital ledger",
        load("natural_orbital_summary.json", data),
        EXPECT_NO_LEDGER,
        errors,
    )

    ratio = load("no_support_ratio.json", data)
    above = [row for row in ratio["records"] if row["no_support_ratio"] > 1]
    if len(above) != EXPECT_NO_RATIO_ABOVE:
        errors.append(
            f"support-ratio above one: expected {EXPECT_NO_RATIO_ABOVE}, got {len(above)}"
        )
    if any(row["regime"] != "INTERFERENCE-GENERIC" for row in above):
        errors.append("support ratio above one should hold only on generic INTERFERENCE")
    flat = [
        row for row in ratio["records"]
        if row["regime"] == "INTERFERENCE-GENERIC" and row["no_support_ratio"] == 1
    ]
    if len(flat) != EXPECT_NO_RATIO_FLAT:
        errors.append(
            f"flat generic records: expected {EXPECT_NO_RATIO_FLAT}, got {len(flat)}"
        )

    check_block(
        "fiber symmetries",
        load("fiber_symmetries.json", data)["summary"],
        EXPECT_FIBER_SYMMETRIES,
        errors,
    )

    if errors:
        print("CAMPAIGN DATA INCONSISTENCIES:")
        for error in errors:
            print("  -", error)
        return 1
    print(
        "campaign artifacts consistent: gauge, cascade, orbit, holonomy, "
        "natural-orbital, v103, and fiber-symmetry claims all hold."
    )
    return 0


if __name__ == "__main__":
    sys.exit(main())
