#!/usr/bin/env python3
"""Census-wide scan of gauge-invariant loop holonomy fields.

For every certified INTERFERENCE state whose support carries loops (a nonzero
integer left-null lattice of the support incidence matrix), this computes the
gauge-invariant holonomies and the number field each holonomy cosine generates.

Setting. The single-particle gauge is U(1)^d: multiplying orbital m by
exp(i phi_m) multiplies the amplitude of determinant T by exp(i sum_{m in T}
phi_m). So for an integer vector k with k^T M = 0 (M the support incidence
matrix, M[T,m] = 1 iff m in T), the loop holonomy

    Phi(k) = sum_T k_T * arg(c_T)

is invariant under the whole gauge group, and cos(Phi(k)) is a gauge-invariant
real algebraic number attached to the state. The lattice of such k is the
integer left kernel of M; a basis of it is a basis of independent loops.

What gets certified per loop:

1. The kernel basis is SATURATED (all invariant factors 1), so the basis
   generates the full integer left kernel and no holonomy relation is missed.
2. cos(Phi) is computed symbolically from the closed form and cross-checked
   numerically at the working precision.
3. The minimal polynomial is obtained two independent ways: exactly with
   sympy minimal_polynomial, and numerically by PSLQ integer relation
   detection on the power vector.
4. THE PRECISION PROTOCOL (non-negotiable, see --precision-lesson): every
   PSLQ-recognized relation is re-verified at twice the working precision and
   the residual is recorded. A genuine relation's residual falls to the
   doubled precision floor; a spurious one stalls near the working precision.
   A relation that fails re-verification is deleted, never downgraded.
5. The Galois group of the minimal polynomial is computed with sympy
   galois_group (not inferred from evenness of the polynomial) and tested for
   2-elementarity, meaning isomorphic to (Z/2)^k.
6. The exact cosine is denested and its radicands extracted, so the
   multiquadratic conclusion is witnessed by explicit square roots of
   rationals rather than only by the Galois group; each radicand class in
   Q*/(Q*)^2 is then tested for membership in the group generated by the
   state weights and denominator. That last test is the STRONGER "square
   roots of rational monomials in the weights" sub-clause of the Holonomy
   Rationality conjecture, and it FAILS on 15 of the 82 loops. The failure is
   expected from the mechanism (the quadratic formula adjoins a square root
   of a discriminant, a polynomial and not a monomial in the weight data) and
   does not touch the multiquadratic conclusion. See docs/holonomy_rationality.md.

The scan also carries a TRISECTION AUDIT of the states the pipeline labels
TRISECTED, showing the label is a property of how the phase is printed rather
than of the state's arithmetic.

Usage:
  python scripts/holonomy_field_scan.py                     # write the artifact
  python scripts/holonomy_field_scan.py --check             # verify it is current
  python scripts/holonomy_field_scan.py --system '(3,10)' --index 17 --stdout
  python scripts/holonomy_field_scan.py --precision-lesson  # reproduce item 5
"""
from __future__ import annotations

import argparse
import json
import re
import sys
from pathlib import Path

import mpmath as mp
import sympy as sp
from sympy.abc import x
from sympy.matrices.normalforms import invariant_factors
from sympy.polys.numberfields.galoisgroups import galois_group

ROOT = Path(__file__).resolve().parents[1]
LEDGER = ROOT / "results" / "data" / "states.jsonl"
OUT = ROOT / "results" / "data" / "holonomy_fields.json"

WORKING_DIGITS = 120
VERIFY_DIGITS = 240
MAX_PSLQ_DEGREE = 8
MAX_PSLQ_COEFF = 10**24


# --------------------------------------------------------------------------
# ledger


def load_states(path: Path = LEDGER):
    return [json.loads(ln) for ln in path.read_text().splitlines() if ln.strip()]


def incidence(dets):
    """Support incidence matrix M, rows = determinants, cols = orbitals."""
    d = max(m for T in dets for m in T) + 1
    return sp.Matrix([[1 if m in T else 0 for m in range(d)] for T in dets]), d


def loop_basis(M):
    """Primitive integer basis of the integer left kernel of M, with a proof
    that it is saturated (generates the full lattice, not a finite-index
    sublattice). Returns (basis, saturated)."""
    basis = []
    for u in M.T.nullspace():
        u = u * sp.lcm([q.q for q in u])
        u = u / sp.gcd([sp.Integer(q) for q in u])
        v = [int(q) for q in u]
        lead = next((c for c in v if c != 0), 1)
        if lead < 0:
            v = [-c for c in v]
        basis.append(v)
    if not basis:
        return [], True
    saturated = all(f == 1 for f in invariant_factors(sp.Matrix(basis)))
    return basis, bool(saturated)


# --------------------------------------------------------------------------
# arithmetic helpers


def squarefree_class(n: int) -> dict[int, int]:
    """Prime exponent vector mod 2 of a positive integer, as {prime: 1}."""
    cls = {}
    for p, e in sp.factorint(sp.Integer(abs(n))).items():
        if e % 2:
            cls[int(p)] = 1
    return cls


def squarefree_part(n: int) -> int:
    """Positive squarefree kernel of |n|, the representative of its class in
    Q*/(Q*)^2."""
    sf = 1
    for p, e in sp.factorint(sp.Integer(abs(n))).items():
        if e % 2:
            sf *= int(p)
    return sf


def radicands(expr):
    """Squarefree radicands of every square root appearing in expr.

    Returns a sorted list, or None if the expression is not built purely from
    rationals, sums, products and square roots of rationals. A non-None return
    is a syntactic witness that the value lies in a multiquadratic extension of
    Q, independent of the Galois group computation.
    """
    found: set[int] = set()

    def walk(e) -> bool:
        if e.is_Rational:
            return True
        if e.is_Add or e.is_Mul:
            return all(walk(a) for a in e.args)
        if e.is_Pow:
            base, power = e.args
            if base.is_Rational and power.is_Rational and abs(power.q) == 2:
                r = sp.Rational(base)
                # sqrt(a/b) and sqrt(a*b) generate the same quadratic field
                sf = squarefree_part(int(r.p) * int(r.q))
                if sf > 1:
                    found.add(sf)
                return True
            return False
        return False

    # walk the expression as given; retry once on a denested form. nsimplify is
    # deliberately NOT used here: it re-nests (sqrt(2) - sqrt(42))/8 back into
    # sqrt(11/16 - sqrt(21)/16), which hides the multiquadratic witness.
    for candidate in (sp.expand(expr), sp.sqrtdenest(sp.expand(expr))):
        found.clear()
        if walk(candidate):
            return sorted(found)
    return None


def in_weight_group(radicand: int, weights: list[int], den: int):
    """Is the class of `radicand` in Q*/(Q*)^2 generated by the weights and den?

    Returns (bool, exponent list over [weights..., den]) via F2 linear algebra
    on prime exponent vectors. This is the "square roots of rational monomials
    in the weights" clause of the Holonomy Rationality conjecture, tested
    rather than assumed.
    """
    gens = [int(w) for w in weights] + [int(den)]
    primes = set()
    for g in gens + [radicand]:
        primes |= set(squarefree_class(abs(g)))
    primes = sorted(primes)
    if not primes:
        return True, [0] * len(gens)
    cols = []
    for g in gens:
        c = squarefree_class(abs(g))
        cols.append([c.get(p, 0) for p in primes])
    tgt = squarefree_class(abs(radicand))
    target = [tgt.get(p, 0) for p in primes]
    # Gaussian elimination over F2 on the matrix whose columns are cols.
    rows = len(primes)
    aug = [[cols[j][i] for j in range(len(gens))] + [target[i]] for i in range(rows)]
    pivots = []
    r = 0
    for c in range(len(gens)):
        pr = next((i for i in range(r, rows) if aug[i][c]), None)
        if pr is None:
            continue
        aug[r], aug[pr] = aug[pr], aug[r]
        for i in range(rows):
            if i != r and aug[i][c]:
                aug[i] = [(a ^ b) for a, b in zip(aug[i], aug[r])]
        pivots.append(c)
        r += 1
        if r == rows:
            break
    for i in range(r, rows):
        if aug[i][-1]:
            return False, None
    expo = [0] * len(gens)
    for i, c in enumerate(pivots):
        expo[c] = aug[i][-1]
    return True, expo


def group_name(G) -> str:
    """Readable name for the small Galois groups that occur here."""
    n = G.order()
    if n == 1:
        return "C1"
    if n == 2:
        return "C2"
    elementary = all(g.order() in (1, 2) for g in G.elements)
    if n == 4:
        return "V4" if elementary else "C4"
    if G.is_abelian:
        return f"A{n}(elementary)" if elementary else f"A{n}"
    return f"nonabelian order {n}"


def is_two_elementary(G) -> bool:
    """G isomorphic to (Z/2)^k: abelian of exponent dividing 2."""
    n = G.order()
    if n & (n - 1):
        return False
    return G.is_abelian and all(g.order() in (1, 2) for g in G.elements)


# --------------------------------------------------------------------------
# PSLQ with the mandatory double-precision re-verification


def to_mpf(expr, digits: int):
    """Evaluate an exact real algebraic expression to `digits` decimals as an
    mpmath float, going through sympy's arbitrary-precision evaluator."""
    return mp.mpf(str(sp.N(expr, digits)))


def pslq_minpoly(value_expr, working: int, verify: int, max_degree: int = MAX_PSLQ_DEGREE):
    """Recognize an integer relation on powers of a real algebraic number.

    Searches increasing degree at `working` digits, then RE-VERIFIES the hit at
    `verify` digits (>= 2 * working by convention). Returns a dict including
    the residual at the verification precision, or None if nothing survives.

    Acceptance: log10(residual) <= -(working + verify) / 2. A genuine relation
    lands near 10^-verify; a spurious one stalls near 10^-working. The midpoint
    separates them with a wide margin at the precisions used here.
    """
    mp.mp.dps = working + 15
    val = to_mpf(value_expr, working + 25)
    tol = mp.mpf(10) ** (-(working - 8))

    # PSLQ needs a vector of nonzero numbers, so a vanishing holonomy cosine is
    # recognized directly: the relation is x, re-verified the same way.
    if abs(val) < tol:
        mp.mp.dps = verify + 15
        residual = abs(to_mpf(value_expr, verify + 25))
        mp.mp.dps = working + 15
        if residual >= mp.mpf(10) ** (-(working + verify) // 2):
            return None
        return {
            "degree": 1,
            "coeffs_ascending": [0, 1],
            "residual": mp.nstr(residual, 6),
            "residual_log10": (
                float(mp.log(residual, 10)) if residual > 0 else float("-inf")
            ),
            "working_digits": working,
            "verify_digits": verify,
        }

    for n in range(1, max_degree + 1):
        rel = mp.pslq(
            [val**j for j in range(n + 1)],
            maxcoeff=MAX_PSLQ_COEFF,
            maxsteps=10**6,
            tol=tol,
        )
        if not rel:
            continue
        if rel[-1] == 0:  # degenerate: relation lives at a lower degree
            continue
        mp.mp.dps = verify + 15
        v2 = to_mpf(value_expr, verify + 25)
        residual = abs(sum(mp.mpf(rel[j]) * v2**j for j in range(n + 1)))
        threshold = mp.mpf(10) ** (-(working + verify) // 2)
        accepted = residual < threshold
        mp.mp.dps = working + 15
        if not accepted:
            # protocol: a relation that fails re-verification is deleted.
            continue
        coeffs = [int(c) for c in rel]
        if coeffs[-1] < 0:
            coeffs = [-c for c in coeffs]
        return {
            "degree": n,
            "coeffs_ascending": coeffs,
            "residual": mp.nstr(residual, 6),
            "residual_log10": (
                float(mp.log(residual, 10)) if residual > 0 else float("-inf")
            ),
            "working_digits": working,
            "verify_digits": verify,
        }
    return None


# --------------------------------------------------------------------------
# per-loop analysis


def analyze_state(rec, working=WORKING_DIGITS, verify=VERIFY_DIGITS):
    cf = rec["closed_form"]
    dets = [tuple(t) for t in cf["support_dets"]]
    M, d = incidence(dets)
    basis, saturated = loop_basis(M)
    if not basis:
        return []
    amps = [sp.sympify(p) for p in cf["pretty"]]
    phases = [sp.arg(a) for a in amps]
    weights = cf["weights"]
    den = cf["den"]
    rational_weights = all(isinstance(w, int) for w in weights)

    rows = []
    for li, k in enumerate(basis):
        Phi = sp.simplify(sum(k[i] * phases[i] for i in range(len(k))))
        cos_exact = sp.simplify(sp.expand_trig(sp.cos(Phi)))
        cos_exact = sp.radsimp(sp.sqrtdenest(sp.nsimplify(cos_exact)))

        # numeric cross-check of the symbolic simplification
        mp.mp.dps = working + 15
        direct = sp.N(sp.cos(sum(k[i] * phases[i] for i in range(len(k)))), working)
        simplified = sp.N(cos_exact, working)
        agree = abs(sp.Float(direct) - sp.Float(simplified)) < sp.Float(10) ** (-(working - 10))

        mpoly = sp.Poly(sp.minimal_polynomial(cos_exact, x), x)
        degree = mpoly.degree()
        exact_coeffs = [int(c) for c in reversed(mpoly.all_coeffs())]
        if exact_coeffs[-1] < 0:
            exact_coeffs = [-c for c in exact_coeffs]

        pslq = pslq_minpoly(cos_exact, working, verify)
        pslq_agrees = bool(pslq) and pslq["coeffs_ascending"] == exact_coeffs

        if degree == 1:
            gname, two_elem, gorder = "C1", True, 1
        else:
            G, _ = galois_group(mpoly)
            gname, two_elem, gorder = group_name(G), is_two_elementary(G), int(G.order())

        rads = radicands(cos_exact)
        memberships = []
        if rads is not None and rational_weights:
            for rad in rads:
                ok, expo = in_weight_group(rad, weights, den)
                memberships.append({"radicand": rad, "in_weight_group": ok, "exponents_f2": expo})

        rows.append(
            {
                "system": rec["system"],
                "index": rec["index"],
                "loop": li,
                "support_size": len(dets),
                "kernel_vector": k,
                "active_dets": [list(dets[i]) for i in range(len(k)) if k[i] != 0],
                "loops_in_state": len(basis),
                "kernel_saturated": saturated,
                "holonomy_exact": sp.srepr(Phi) if Phi.free_symbols else str(Phi),
                "cos_exact": str(cos_exact),
                "cos_numeric_30": str(sp.N(cos_exact, 30)),
                "symbolic_numeric_agree": bool(agree),
                "min_poly": str(mpoly.as_expr()),
                "min_poly_coeffs_ascending": exact_coeffs,
                "degree": degree,
                "galois_group": gname,
                "galois_order": gorder,
                "two_elementary": bool(two_elem),
                "pslq": pslq,
                "pslq_confirms_exact": pslq_agrees,
                "radicands": rads,
                "multiquadratic_witness": rads is not None,
                "radicand_weight_group": memberships,
                "weights": weights,
                "den": den,
                "rational_weights": rational_weights,
            }
        )
    return rows


# --------------------------------------------------------------------------
# the precision lesson, reproduced as a certified artifact


def precision_lesson(system="(5,10)", index=144, loop=1):
    """Reproduce the PSLQ precision failure mode that produced a false
    counterexample in the exploratory session.

    At low working precision, PSLQ on a degree-7 power lattice returns a
    relation with large, structureless coefficients whose residual only reaches
    the working precision. Re-verification at doubled precision separates it
    from the true relation, whose residual reaches the doubled precision. This
    is the evidence behind the mandatory re-verification step.
    """
    rec = next(
        r
        for r in load_states()
        if r["system"] == system and r["index"] == index
    )
    cf = rec["closed_form"]
    dets = [tuple(t) for t in cf["support_dets"]]
    M, _ = incidence(dets)
    basis, _ = loop_basis(M)
    phases = [sp.arg(sp.sympify(p)) for p in cf["pretty"]]
    k = basis[loop]
    cos_exact = sp.simplify(sp.expand_trig(sp.cos(sum(k[i] * phases[i] for i in range(len(k))))))

    trials = []
    for dps in (20, 30, 40, 60, 120):
        mp.mp.dps = dps + 10
        val = to_mpf(cos_exact, dps + 25)
        rel = mp.pslq(
            [val**j for j in range(8)],
            maxcoeff=10**30,
            maxsteps=10**6,
            tol=mp.mpf(10) ** (-dps),
        )
        if not rel:
            trials.append({"working_digits": dps, "relation": None})
            continue
        mp.mp.dps = 2 * dps + 40
        v2 = to_mpf(cos_exact, 2 * dps + 60)
        res = abs(sum(mp.mpf(rel[j]) * v2**j for j in range(8)))
        trials.append(
            {
                "working_digits": dps,
                "verify_digits": 2 * dps,
                "relation": [int(c) for c in rel],
                "residual": mp.nstr(res, 5),
                "residual_log10": float(mp.log(res, 10)) if res > 0 else float("-inf"),
                "reaches_verify_precision": bool(res < mp.mpf(10) ** (-1.5 * dps)),
            }
        )
    mp.mp.dps = 15
    return {
        "system": system,
        "index": index,
        "loop": loop,
        "cos_exact": str(cos_exact),
        "true_min_poly": str(sp.minimal_polynomial(cos_exact, x)),
        "search_degree": 7,
        "trials": trials,
        "lesson": (
            "PSLQ hits at 20 to 40 digits are structureless and their residuals "
            "stall at the working precision; the true relation appears at 60 "
            "digits and its residual falls to the doubled precision. Every "
            "recognized relation must therefore be re-verified at at least "
            "double the working precision, with the residual recorded. A "
            "relation that fails re-verification is deleted, not downgraded."
        ),
    }


# --------------------------------------------------------------------------
# the trisection audit


def trisection_audit(loops_rows):
    """Audit the states the pipeline labels TRISECTED.

    scripts/reproduce_next_claims.py assigns the TRISECTED phase tier by a
    SYNTACTIC test on the printed closed form ("atan" and "/3" both present).
    This checks what is actually there: the degree over Q of every
    representative amplitude, and the minimal polynomial of every
    gauge-invariant loop holonomy of the same state.

    The written phase (pi + 3*atan(t))/3 equals pi/3 + atan(t); the division by
    three cancels, so no cube root survives the simplification. The audit
    records this rather than asserting it.
    """
    by_state = {}
    for r in loops_rows:
        by_state.setdefault((r["system"], r["index"]), []).append(r)

    out = []
    for rec in load_states():
        pretty = [str(p) for p in rec["closed_form"]["pretty"]]
        joined = " ".join(pretty)
        if not (re.search(r"\bI\b", joined) and "atan" in joined and "/3" in joined):
            continue
        degrees = set()
        for p in pretty:
            e = sp.sympify(p)
            e = sp.expand(sp.re(e)) + sp.I * sp.expand(sp.im(e))
            degrees.add(int(sp.minimal_polynomial(sp.simplify(e), x).as_poly(x).degree()))
        loops = by_state.get((rec["system"], rec["index"]), [])
        out.append(
            {
                "system": rec["system"],
                "index": rec["index"],
                "amplitude_degrees_over_Q": sorted(degrees),
                "all_degrees_are_powers_of_two": all(d & (d - 1) == 0 for d in degrees),
                "any_degree_divisible_by_three": any(d % 3 == 0 for d in degrees),
                "holonomy_min_polys": [loop["min_poly"] for loop in loops],
                "holonomy_degrees": [loop["degree"] for loop in loops],
                "holonomy_galois_groups": [loop["galois_group"] for loop in loops],
            }
        )
    return {
        "tier_definition": (
            "syntactic: the printed closed form contains both 'atan' and '/3' "
            "(scripts/reproduce_next_claims.py::two_block_phase_census)"
        ),
        "states": len(out),
        "no_cubic_anywhere": all(
            not s["any_degree_divisible_by_three"] and s["all_degrees_are_powers_of_two"]
            for s in out
        ),
        "all_holonomies_degree_1_2_4": all(
            all(d in (1, 2, 4) for d in s["holonomy_degrees"]) for s in out
        ),
        "finding": (
            "The TRISECTED tier is an artifact of how the amplitude phase is "
            "printed, not a phase-complexity tier. (pi + 3*atan(t))/3 reduces "
            "to pi/3 + atan(t); every representative amplitude of every state "
            "in the tier has 2-power degree over Q, and every gauge-invariant "
            "loop holonomy of those states is rational or multiquadratic. No "
            "cubic subextension occurs anywhere in the class."
        ),
        "records": out,
    }


# --------------------------------------------------------------------------
# driver


def build(working=WORKING_DIGITS, verify=VERIFY_DIGITS, only=None):
    rows = []
    for rec in load_states():
        if rec["classified"] != "INTERFERENCE":
            continue
        if only and (rec["system"], rec["index"]) != only:
            continue
        rows.extend(analyze_state(rec, working, verify))

    states = sorted({(r["system"], r["index"]) for r in rows})
    degrees = {}
    groups = {}
    for r in rows:
        degrees[str(r["degree"])] = degrees.get(str(r["degree"]), 0) + 1
        groups[r["galois_group"]] = groups.get(r["galois_group"], 0) + 1

    summary = {
        "loopy_states": len(states),
        "loops": len(rows),
        "degree_counts": dict(sorted(degrees.items(), key=lambda kv: int(kv[0]))),
        "galois_group_counts": dict(sorted(groups.items())),
        "all_degrees_in_1_2_4": all(r["degree"] in (1, 2, 4) for r in rows),
        "all_two_elementary": all(r["two_elementary"] for r in rows),
        "all_kernels_saturated": all(r["kernel_saturated"] for r in rows),
        "all_symbolic_numeric_agree": all(r["symbolic_numeric_agree"] for r in rows),
        "all_pslq_reverified": all(r["pslq"] is not None for r in rows),
        "all_pslq_confirm_exact": all(r["pslq_confirms_exact"] for r in rows),
        "all_multiquadratic_witnessed": all(r["multiquadratic_witness"] for r in rows),
        "all_radicands_in_weight_group": all(
            all(m["in_weight_group"] for m in r["radicand_weight_group"])
            for r in rows
            if r["rational_weights"]
        ),
        "loops_with_radicand_outside_weight_group": sum(
            1
            for r in rows
            if any(not m["in_weight_group"] for m in r["radicand_weight_group"])
        ),
        "worst_pslq_residual_log10": max(
            (r["pslq"]["residual_log10"] for r in rows if r["pslq"]), default=None
        ),
    }
    summary["weight_group_note"] = (
        "all_radicands_in_weight_group tests the STRONGER sub-clause of the "
        "Holonomy Rationality conjecture, that every adjoined square root is of "
        "a rational MONOMIAL in the weights. It is false: "
        f"{summary['loops_with_radicand_outside_weight_group']} of {len(rows)} "
        "loops adjoin a square root whose squarefree class is outside the group "
        "generated by the weights and the denominator. The mechanism is the "
        "quadratic formula: solving A cos(Phi) + B sin(Phi) + C = 0 adjoins "
        "sqrt(A^2 + B^2 - C^2), a POLYNOMIAL and not a monomial in the weight "
        "data, and later loops see the sines of earlier ones. The conjecture's "
        "actual conclusion, that the field is multiquadratic, is unaffected and "
        "holds on every loop. See docs/holonomy_rationality.md."
    )
    return {
        "generated_by": "scripts/holonomy_field_scan.py",
        "ledger": "results/data/states.jsonl",
        "what": (
            "Gauge-invariant loop holonomy cosines of every certified "
            "INTERFERENCE state whose support carries loops, with the number "
            "field each generates."
        ),
        "precision_protocol": {
            "working_digits": working,
            "verify_digits": verify,
            "rule": (
                "Every PSLQ-recognized relation is re-verified at the "
                "verification precision and accepted only if its residual is "
                "below 10^-((working+verify)/2). A relation that fails "
                "re-verification is deleted, not downgraded."
            ),
            "evidence": "see --precision-lesson and the precision_lesson block",
        },
        "summary": summary,
        "trisection_audit": trisection_audit(rows),
        "precision_lesson": precision_lesson(),
        "loops": rows,
    }


def main():
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("--out", default=str(OUT))
    ap.add_argument("--digits", type=int, default=WORKING_DIGITS)
    ap.add_argument("--verify-digits", type=int, default=VERIFY_DIGITS)
    ap.add_argument("--system")
    ap.add_argument("--index", type=int)
    ap.add_argument("--stdout", action="store_true", help="print instead of writing")
    ap.add_argument("--check", action="store_true", help="fail if the artifact is stale")
    ap.add_argument("--precision-lesson", action="store_true")
    a = ap.parse_args()

    if a.precision_lesson:
        print(json.dumps(precision_lesson(), indent=2))
        return 0

    only = None
    if a.system is not None and a.index is not None:
        sysname = a.system if a.system.startswith("(") else f"({a.system})"
        only = (sysname, a.index)

    doc = build(a.digits, a.verify_digits, only)
    text = json.dumps(doc, indent=1, sort_keys=False) + "\n"

    if a.stdout or only:
        print(text)
        return 0
    if a.check:
        cur = Path(a.out).read_text() if Path(a.out).exists() else ""
        if cur != text:
            print(f"STALE: {a.out} does not match a fresh scan", file=sys.stderr)
            return 1
        print(f"{a.out} is current")
        return 0

    Path(a.out).write_text(text)
    s = doc["summary"]
    print(f"wrote {a.out}")
    print(f"  states {s['loopy_states']}  loops {s['loops']}")
    print(f"  degrees {s['degree_counts']}")
    print(f"  galois  {s['galois_group_counts']}")
    for key in (
        "all_degrees_in_1_2_4",
        "all_two_elementary",
        "all_kernels_saturated",
        "all_symbolic_numeric_agree",
        "all_pslq_reverified",
        "all_pslq_confirm_exact",
        "all_multiquadratic_witnessed",
        "all_radicands_in_weight_group",
    ):
        print(f"  {key}: {s[key]}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
