#!/usr/bin/env python3
"""Does first-order fixed-rho rigidity imply rational squared weights?

For every census record, join two things: whether the state is first-order
rigid in the FIXED-RHO fiber (`fixed_rho_tangent_dim == 0`, from
results/data/cascade.jsonl) and whether its squared weights are rational (from
the shipped closed form, whose weights are integers over an integer
denominator when rational and exact radical strings otherwise).

The implication under test is

    FIXED-RHO RIGID  =>  RATIONAL SQUARED WEIGHTS

which is the empirical shadow of the Rigidity-Rationality target in
docs/rigidity_rationality.md: a fiber that is a single point modulo gauge is
cut out by equations with rational coefficients, and a Galois-stable singleton
is Galois-fixed, hence rational.

SCOPE WARNING, recorded in the artifact. 154 of the 799 shipped records are
not natural-orbital representatives: their 1-RDM is not diagonal, so they
attain the spectrum in another basis (results/data/attainer_gate_audit.json).
Both the rigidity datum and the weight datum are measured on the shipped
representative, so for those 154 the implication is a statement about that
representative and not about the vertex. The 645 gate-passing records are the
subset on which the statement is about a natural-orbital representative, and
the tally is reported separately for them.

Usage:
  python scripts/rigidity_rationality_census.py           # write the artifact
  python scripts/rigidity_rationality_census.py --check
"""
from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

import sympy as sp

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "src"))

DATA = ROOT / "results" / "data"
OUT = DATA / "rigidity_rationality.json"


def _keyed(name):
    return {
        (r["system"], r["index"]): r
        for r in (
            json.loads(ln)
            for ln in (DATA / name).read_text().splitlines()
            if ln.strip()
        )
    }


def weight_field(record):
    """Degree over Q of the field generated by the squared weights.

    The shipped closed form stores integer weights over an integer denominator
    when the squared weights are rational, and exact radical strings otherwise.
    Rather than trusting the encoding, this recomputes the field from the
    values: degree 1 means every squared weight is rational.
    """
    cf = record["closed_form"]
    den = cf["den"]
    values = []
    for w in cf["weights"]:
        values.append(sp.nsimplify(sp.sympify(w)) / den if not isinstance(w, int)
                      else sp.Rational(w, den))
    rational = all(v.is_Rational for v in values)
    if rational:
        return {"rational": True, "degree": 1, "generators": []}

    irrational = [v for v in values if not v.is_Rational]
    degrees = sorted(
        {int(sp.minimal_polynomial(v, sp.Symbol("x")).as_poly().degree()) for v in irrational}
    )
    radicands = set()
    for v in irrational:
        for atom in sp.sympify(v).atoms(sp.Pow):
            base, power = atom.args
            if base.is_Rational and power.is_Rational and abs(power.q) == 2:
                r = sp.Rational(base)
                sf = 1
                for p, e in sp.factorint(sp.Integer(abs(int(r.p) * int(r.q)))).items():
                    if e % 2:
                        sf *= int(p)
                if sf > 1:
                    radicands.add(sf)
    return {
        "rational": False,
        "degree": max(degrees) if degrees else None,
        "generators": sorted(radicands),
    }


def build():
    states = _keyed("states.jsonl")
    cascade = _keyed("cascade.jsonl")
    gate = {
        (r["system"], r["index"]): r
        for r in json.loads((DATA / "attainer_gate_audit.json").read_text())["records"]
    }

    rows = []
    for key, rec in sorted(states.items()):
        casc = cascade[key]
        field = weight_field(rec)
        rows.append(
            {
                "system": key[0],
                "index": key[1],
                "label": f"{key[0]} v{key[1]}",
                "classified": rec["classified"],
                "fixed_rho_tangent_dim": casc["fixed_rho_tangent_dim"],
                "fixed_spectrum_tangent_dim": casc["fixed_spectrum_tangent_dim"],
                "fixed_rho_rigid": casc["fixed_rho_tangent_dim"] == 0,
                "rational_weights": field["rational"],
                "weight_field_degree": field["degree"],
                "weight_field_generators": field["generators"],
                "passes_attainer_gate": gate[key]["passes_gate"],
                "evidence": "rigidity NUMERICAL (cascade.jsonl); weight field EXACT",
            }
        )

    def tally(sel):
        rigid = [r for r in sel if r["fixed_rho_rigid"]]
        deformable = [r for r in sel if not r["fixed_rho_rigid"]]
        rigid_irrational = [r for r in rigid if not r["rational_weights"]]
        return {
            "states": len(sel),
            "rigid": len(rigid),
            "deformable": len(deformable),
            "rigid_and_rational": sum(1 for r in rigid if r["rational_weights"]),
            "rigid_and_irrational": len(rigid_irrational),
            "counterexample_labels": [r["label"] for r in rigid_irrational],
            "implication_holds": not rigid_irrational,
            "deformable_and_rational": sum(
                1 for r in deformable if r["rational_weights"]
            ),
            "deformable_and_irrational": sum(
                1 for r in deformable if not r["rational_weights"]
            ),
            "irrational_labels": [r["label"] for r in sel if not r["rational_weights"]],
        }

    everything = tally(rows)
    gated = tally([r for r in rows if r["passes_attainer_gate"]])

    return {
        "generated_by": "scripts/rigidity_rationality_census.py",
        "claim": "fixed-rho first-order rigid implies rational squared weights",
        "evidence": (
            "Rigidity is NUMERICAL, inherited from cascade.jsonl. The weight "
            "field is EXACT, recomputed from the closed form rather than read "
            "off the integer-versus-string encoding."
        ),
        "all_records": everything,
        "gate_passing_records_only": gated,
        "scope_warning": (
            "154 of the 799 shipped records are not natural-orbital "
            "representatives (results/data/attainer_gate_audit.json): their "
            "1-RDM is not diagonal, so they attain the spectrum in another "
            "basis. Both the rigidity and the weight datum are properties of "
            "the shipped representative, so on those records the implication "
            "is a statement about that representative and not about the "
            "vertex. gate_passing_records_only is the subset where the "
            "statement is about a natural-orbital representative."
        ),
        "direction_check": (
            "Deformability does not force irrationality: the deformable class "
            "is overwhelmingly rational too, so the implication is one-way "
            "evidence and not a biconditional."
        ),
        "power_warning": {
            "finding": (
                "Every one of the 645 natural-orbital representatives is "
                "fixed-rho rigid, and all 59 deformable records are among the "
                "154 that fail the gate."
            ),
            "consequence": (
                "The implication's discriminating power lives ENTIRELY in the "
                "records that are not natural-orbital representatives. On the "
                "645 gate-passing records the antecedent is always true, so "
                "the implication is confirmed there without any rigid-versus-"
                "deformable contrast to confirm it against. Quoting 740 of 740 "
                "as evidence for a statement about vertices overstates it in "
                "the same way the bracket holdout's 38 rows did: the count is "
                "right and the independent content is smaller."
            ),
            "mechanism": (
                "Expected rather than surprising. The fixed-rho fiber fixes "
                "rho itself, and a record whose rho is not diag(lambda) is "
                "constrained differently from one whose rho is, so the two "
                "populations are not comparable observations of one law."
            ),
        },
        "records": rows,
    }


def main():
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("--out", default=str(OUT))
    ap.add_argument("--check", action="store_true")
    a = ap.parse_args()

    doc = build()
    text = json.dumps(doc, indent=1) + "\n"
    if a.check:
        cur = Path(a.out).read_text() if Path(a.out).exists() else ""
        if cur != text:
            print(f"STALE: {a.out}", file=sys.stderr)
            return 1
        print(f"{a.out} is current")
        return 0

    Path(a.out).write_text(text)
    for name in ("all_records", "gate_passing_records_only"):
        t = doc[name]
        print(f"{name}:")
        print(f"  states {t['states']}  rigid {t['rigid']}  deformable {t['deformable']}")
        print(f"  rigid and rational   : {t['rigid_and_rational']}")
        print(f"  rigid and irrational : {t['rigid_and_irrational']} "
              f"{t['counterexample_labels']}")
        print(f"  implication holds    : {t['implication_holds']}")
        print(f"  irrational records   : {t['irrational_labels']}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
